// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PymeCafe.Models;

#nullable disable

namespace PymeCafe.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241209175921_RemoveImagenColumn")]
    partial class RemoveImagenColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PymeCafe.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("NombreCategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__CATEGORI__F353C1C50B531DE6");

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Detallespedido", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("PedidoID");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.HasKey("DetalleId")
                        .HasName("PK__DETALLES__6E19D6FA2F11F711");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DETALLESPEDIDO", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificacionId")
                        .HasName("PK__NOTIFICA__BCC120C44EAC3A5D");

                    b.HasIndex("UserId");

                    b.ToTable("NOTIFICACION", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PedidoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EstadoPedido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("FechaPedido")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PedidoId")
                        .HasName("PK__PEDIDO__09BA1410549D09D4");

                    b.HasIndex("UserId");

                    b.ToTable("PEDIDO", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreProducto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductoId")
                        .HasName("PK__PRODUCTO__A430AE836D9441A6");

                    b.HasIndex("CategoriaId");

                    b.ToTable("PRODUCTO", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Publicacion", b =>
                {
                    b.Property<int>("PublicacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicacionID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("PublicacionID");

                    b.ToTable("Publicacion");
                });

            modelBuilder.Entity("PymeCafe.Models.Puntosdelealtad", b =>
                {
                    b.Property<int>("PuntosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PuntosID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuntosId"));

                    b.Property<int?>("PuntosAcumulados")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PuntosId")
                        .HasName("PK__PUNTOSDE__77F5142BC519A10E");

                    b.HasIndex("UserId");

                    b.ToTable("PUNTOSDELEALTAD", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Recomendacion", b =>
                {
                    b.Property<int>("RecomendacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecomendacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecomendacionId"));

                    b.Property<DateTime?>("FechaRecomendacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RecomendacionId")
                        .HasName("PK__RECOMEND__104CC1EEF8107DE6");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UserId");

                    b.ToTable("RECOMENDACION", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Usuario", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__USUARIO__1788CCACCE9AC0A3");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Valoracionesdeproducto", b =>
                {
                    b.Property<int>("ValoracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ValoracionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValoracionId"));

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ValoracionId")
                        .HasName("PK__VALORACI__BFB912DD1AC85966");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UserId");

                    b.ToTable("VALORACIONESDEPRODUCTO", (string)null);
                });

            modelBuilder.Entity("PymeCafe.Models.Detallespedido", b =>
                {
                    b.HasOne("PymeCafe.Models.Pedido", "Pedido")
                        .WithMany("Detallespedidos")
                        .HasForeignKey("PedidoId")
                        .HasConstraintName("FK__DETALLESP__Pedid__412EB0B6");

                    b.HasOne("PymeCafe.Models.Producto", "Producto")
                        .WithMany("Detallespedidos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__DETALLESP__Produ__4222D4EF");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PymeCafe.Models.Notificacion", b =>
                {
                    b.HasOne("PymeCafe.Models.Usuario", "User")
                        .WithMany("Notificacions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__NOTIFICAC__UserI__48CFD27E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PymeCafe.Models.Pedido", b =>
                {
                    b.HasOne("PymeCafe.Models.Usuario", "User")
                        .WithMany("Pedidos")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__PEDIDO__UserID__398D8EEE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PymeCafe.Models.Producto", b =>
                {
                    b.HasOne("PymeCafe.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__PRODUCTO__Catego__3E52440B");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PymeCafe.Models.Puntosdelealtad", b =>
                {
                    b.HasOne("PymeCafe.Models.Usuario", "User")
                        .WithMany("Puntosdelealtads")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__PUNTOSDEL__UserI__4BAC3F29");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PymeCafe.Models.Recomendacion", b =>
                {
                    b.HasOne("PymeCafe.Models.Producto", "Producto")
                        .WithMany("Recomendacions")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__RECOMENDA__Produ__45F365D3");

                    b.HasOne("PymeCafe.Models.Usuario", "User")
                        .WithMany("Recomendacions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__RECOMENDA__UserI__44FF419A");

                    b.Navigation("Producto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PymeCafe.Models.Valoracionesdeproducto", b =>
                {
                    b.HasOne("PymeCafe.Models.Producto", "Producto")
                        .WithMany("Valoracionesdeproductos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__VALORACIO__Produ__4E88ABD4");

                    b.HasOne("PymeCafe.Models.Usuario", "User")
                        .WithMany("Valoracionesdeproductos")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__VALORACIO__UserI__4F7CD00D");

                    b.Navigation("Producto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PymeCafe.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PymeCafe.Models.Pedido", b =>
                {
                    b.Navigation("Detallespedidos");
                });

            modelBuilder.Entity("PymeCafe.Models.Producto", b =>
                {
                    b.Navigation("Detallespedidos");

                    b.Navigation("Recomendacions");

                    b.Navigation("Valoracionesdeproductos");
                });

            modelBuilder.Entity("PymeCafe.Models.Usuario", b =>
                {
                    b.Navigation("Notificacions");

                    b.Navigation("Pedidos");

                    b.Navigation("Puntosdelealtads");

                    b.Navigation("Recomendacions");

                    b.Navigation("Valoracionesdeproductos");
                });
#pragma warning restore 612, 618
        }
    }
}
